<?php
return [
    'default' => [
    ],
    'navbar' => [
        'home' => '首页',
        'courses' => '课程',
        'advice' => '咨询',
        'rent' => '租赁',
        'contact' => '联系',
    ],
    'footer' => [
        'h3' => 'Gyors linkek',
        'home' => '首页',
        'courses' => '课程',
        'advice' => '咨询',
        'rent' => '租赁',
        'about-us' => 'Rólunk',
        'contact' => '联系',
    ],
    'follow_us' => "Kövess minket",
        'contact' => [
    ],
    'documents' => [
        'h2' => 'Jelentkezéshez szükséges dokumentumok',
        'li1' => 'Személyazonosító igazolvány',
        'li2' => 'Lakcímkártya',
        'li3' => 'Szakmai irányító bizonyítvány (első sikeres vizsgát igazoló dokumentum)',
        'note_label' => 'Kiemelten fontos:',
        'note' => 'A vizsgára csak az eredeti bizonyítvány bemutatásával lehet jelentkezni, másolatot a Vizsgaközpont nem fogad el!',
    ],
    'data' => [
        'h3' => 'Adatok',
        'tax-number' => 'Adószám',
        'company-registration-number' => 'Cégjegyzékszám',
        'registration-number' => 'Nyilvántartási szám',
        'gdpr-contact-person' => 'GDPR kapcsolattartó',
    ],
    'header' => [
        'video' => 'A videó nem elérhető ebben a böngészőben.',
        'h1' => 'Komplex képzési megoldások fuvarozóknak',
        'subtitle' => 'GKI, ADR tanfolyamok és szakmai irányítói képzés egy helyen',
        'button' => 'Tanfolyamaink',
    ],
    'courses' => [
        'h2' => 'Tanfolyamaink',
        'h3' => 'Osztrák ADR tanfolyam',
        'p' => 'Ausztriában végzett, hivatalos veszélyesáru-szállítási képzések magyar nyelven.',
    ],
    'courses-in-hungary' => [
        'h3' => 'Magyarországi tanfolyamok',
        'p' => 'Magyarországon elérhető felnőttképzések a közlekedési, fuvarozási szektor számára.',
    ],
    'hungarian-adr-course' => [
        'h3' => 'Magyarországi ADR tanfolyam',
        'p' => 'Az ADR 1.3. fejezete szerinti „kisadr” képzés.',
    ],
    'about-us' => [
        'about-us' => 'Rólunk',
        'p' => 'Több mint két évtizedes tapasztalatunkkal nem csupán szolgáltatást, hanem valódi, értékalapú partnerséget kínálunk. Minden ügyfelünkkel egyedi úton járunk: megértjük működésüket, céljaikat és a hozzájuk vezető legbiztonságosabb utat. Hiszünk abban, hogy az igazi szakmaiság nem sablonokban, hanem személyre szabott megoldásokban mutatkozik meg.',
        'q' => 'Szakértelem, amely előnyt teremt.',
        'button' => 'Munkatársaink',
    ],
    'why-choose' => [
        'h2' => 'Miért válassza a RDR2003-at?',
    ],
    'info2' => [
    ],
    'info3' => [
    ],
    'info4' => [
    ],
    'partners' => [
        'h2' => 'Partnereink',
    ],
    'contact' => [
        'h2' => 'Kérdése van?',
        'p' => 'Forduljon hozzánk bizalommal az elérhetőségeink egyikén!',
        'link' => 'Elérhetőségeink',
    ],
    'button' => 'Küldés'
        ],
        'contact-info' => [
        'h3' => 'Helyszín',
        'address' => 'Törökbálint, Tópark u. 1a, 2045',
        'address-info' => 'Max City bevásárlóközpont és a Shell kút közötti fehér színű irodaház',
    ],
    'opening' => [
        'open' => 'Nyitva',
        'close' => 'Zárva',
        'openingSoon' => 'Hamarosan nyit',
        'closingSoon' => 'Hamarosan zár',
    ],
    'openTime' => 'Nyitvatartás',
            'days' => [
        'monday' => 'Hétfő',
        'tuesday' => 'Kedd',
        'wednesday' => 'Szerda',
        'thursday' => 'Csütörtök',
        'friday' => 'Péntek',
        'saturday' => 'Szombat',
        'sunday' => 'Vasárnap',
    ],
    'cookie' => [
        'info' => 'Ez a weboldal cookie-kat (sütiket) használ a felhasználói élmény javítása érdekében.
                A weboldal használatával Ön elfogadja a cookie-k használatát.
                További információt a ',
        'link' => 'Cookie Tájékoztatóban',
        'button' => 'Elfogadom',
    ],
    'advice-page' => [
        'title' => '咨询',
        'content1' => 'Több mint 20 éve állunk partnereink rendelkezésére az ADR biztonsági tanácsadás területén, folyamatosan bővülő, magasan képzett szakértői csapatunkkal. Számos iparági területen szereztünk mélyreható tapasztalatot, a veszélyes áru szállításának minden szegmensét átfogva. Munkánkat nem sablonok szerint, hanem a cégek egyedi működésére szabva, precízen és naprakész tudással végezzük. Ügyfeleink számára nemcsak jogszabályi megfelelést, hanem valódi biztonságot és üzleti előnyt teremtünk.',
        'h2' => 'Szolgáltatásaink',
        'content2' => 'A 25/2014. (IV. 30.) NFM rendelet előírásai szerint minden vállalkozás, amely Magyarországon veszélyes áru vagy veszélyes hulladék közúti szállításával foglalkozik, köteles legalább egy veszélyesáru-szállítási biztonsági tanácsadót megbízni. Cégünk vállalja a veszélyesáru-szállítási biztonsági tanácsadói feladatok teljes körű ellátását Magyarország egész területén. Segítünk a jogszabályi előírások betartásában, a szállítási folyamatok biztonságos megszervezésében, valamint támogatjuk a hatósági ellenőrzésekre való felkészülést is.',
        'content3' => 'Forduljon hozzánk bizalommal, ha tapasztalt és megbízható szakértőre van szüksége!',
        'info-1-h3' => 'Oktatás',
        'info-1-p' => 'ADR 1.3 fejezete szerinti oktatás.',
        'info-2-h3' => '咨询',
        'info-2-p' => 'Általános tanácsadás.',
        'info-3-h3' => 'Jogszabályok vizsgálata',
        'info-3-p' => 'Jogszabályoknak való megfelelés vizsgálata.',
        'info-4-h3' => 'Telephelyi bejárás',
        'info-4-p' => 'Telephelyi bejárások.',
        'info-5-h3' => 'Csomagolóeszközök tanácsadás',
        'info-5-p' => 'Csomagolóeszközök minősítésével kapcsolatos tanácsadás.',
        'info-6-h3' => 'Felszerelések beszerzése',
        'info-6-p' => 'ADR felszerelések, bárcák, táblák, jelölések beszerzése.',
    ],
    'when-needed' => [
        'h2' => 'A tanácsadó alkalmazása mikor szükséges?',
        'li1' => 'Veszélyes áru telephelyen kívüli szállítása',
        'li2' => 'Veszélyes áru feladása',
        'li3' => 'Veszélyes áru ideiglenes tárolása',
        'li4' => 'A veszélyes áru becsomagolása, töltése, be- és kirakodása, ürítése',
        'li5' => 'Veszélyes hulladékok csomagolása, szállítása, begyűjtése, kirakodása',
    ],
    'rent-page' => [
        'title' => 'Bérbeadás',
        'h3' => 'Személyszállító furgon bérlés',
        'p' => 'Tágas, kényelmes személyszállító furgon 6-9 fő részére, ideális csapatutazásokhoz vagy rendezvényekhez – nem teherszállításra, hanem utazásra tervezve.',
    ],
    'card2' => [
        'h3' => 'Tanterem bérlés',
        'p' => 'Két klimatizált, jól felszerelt tanterem bérelhető tréningekhez, workshopokhoz vagy kisebb rendezvényekhez, modern technikával, cateringgel és kiváló megközelíthetőséggel.',
    ],
    'privacy-page' => [
        'title' => 'GDPR Tájékoztató',
        'h2' => '1. Mi az a GDPR?',
        'p' => 'A GDPR, vagyis az Általános Adatvédelmi Rendelet (General Data Protection Regulation) az Európai Unió 2016/679 számú rendelete, amely 2018. május 25-én lépett hatályba. Célja az EU-n belül élő természetes személyek személyes adatainak védelme és az adatkezelés egységes szabályozása.',
    ],
    'section2' => [
        'h2' => 'Vizsgás GKI tanfolyam',
        'type_label' => 'Képzés típusa: ',
        'type' => 'E-learning (online, E-titán rendszerben) – otthon önállóan elvégezhető.',
        'sim_label' => 'Szimulátoros tanfolyam: ',
        'sim' => '5 óra (kötelező a GKI kártya megszerzéséhez). Időpontot a tanfolyam elkezdése után egyeztetünk.',
        'exam_label' => 'Vizsga: ',
        'exam' => 'Számítógépes vizsga vizsgaközpontban.',
    ],
    'section3' => [
        'h2' => 'Jelentkezéshez szükséges dokumentumok',
        'li1' => 'Személyigazolvány',
        'li2' => 'Lakcímkártya',
        'li3' => 'Jogosítvány (érvényes)',
        'li4' => 'GKI kártya',
        'li5' => 'Telefonszám',
        'li6' => 'E-mail cím (nem elfogadott: freemail.hu, citromail.hu, gmail.hu)',
        'li7' => '1 db igazolványkép',
    ],
    'title' => 'Hozzáférési jog', 'desc' => 'Ön megismerheti, hogy milyen személyes adatokat kezelünk Önről.'],
                ['title' => 'Helyesbítés joga', 'desc' => 'Kérheti pontatlan adatai helyesbítését.'],
                ['title' => 'Törlés joga („az elfeledtetés joga”)', 'desc' => 'Bizonyos esetekben kérheti adatai törlését.'],
                ['title' => 'Adatkezelés korlátozásának joga'],
                ['title' => 'Adathordozhatósághoz való jog'],
                ['title' => 'Tiltakozáshoz való jog', 'desc' => 'Tiltakozhat az adatkezelés ellen, ha az jogos érdeken alapul.'],
                ['title' => 'Automatizált döntéshozatal elleni tiltakozás'],
            ],
        ],
        'section4' => [
        'h2' => '4. Hova fordulhat panasszal?',
        'desc' => 'Ha úgy érzi, hogy jogai sérültek, panaszt tehet az alábbi felügyeleti hatóságnál:',
        'authority' => 'Nemzeti Adatvédelmi és Információszabadság Hatóság (NAIH)',
        'address' => 'Cím: 1055 Budapest, Falk Miksa utca 9-11.',
        'phone' => 'Telefon: +36 (1) 391-1400',
        'email' => 'Email: ugyfelszolgalat@naih.hu',
        'website' => 'Weboldal: <a href="https://www.naih.hu" target="_blank">https://www.naih.hu</a>',
    ],
    'section5' => [
        'h2' => '5. Az adatkezelés időtartama',
        'p' => 'Az adatokat a beérkezéstől számított legfeljebb 12 hónapig tároljuk, vagy addig, amíg Ön nem kéri azok törlését.',
    ],
    'last_updated' => 'Utolsó frissítés dátuma: 2025. január 1.',
    ],
    'cookie-page' => [
        'title' => 'Cookie (Süti) tájékoztató',
        'effective_date' => 'Hatályos: 2025. január 1.',
        'last_updated' => 'Utolsó frissítés: 2025. január 1.',
        'p' => 'Ez a tájékoztató a weboldalon (a továbbiakban: „Weboldal") használt sütikről (cookie-król) ad részletes információt, összhangban az Európai Parlament és a Tanács 2016/679 számú rendeletével (GDPR), valamint a 2003. évi C. törvénnyel az elektronikus hírközlésről.',
    ],
    'section1' => [
        'h2' => '1. Mi az a cookie?',
        'p' => 'A cookie (magyarul: süti) egy kis adatcsomag, amelyet a weboldal az Ön böngészőjén keresztül az Ön számítógépén vagy mobileszközén helyez el, amikor meglátogatja az oldalt. A cookie-k lehetővé teszik a weboldal számára, hogy megismerje és felismerje a visszatérő felhasználót, megjegyezze annak beállításait, és statisztikai vagy marketing célból adatokat gyűjtsön.',
    ],
    'b' => [
        'title' => 'b) Statisztikai vagy analitikai célú cookie-k',
        'p1' => 'Ezek a sütik lehetővé teszik számunkra, hogy anonim módon adatokat gyűjtsünk arról, hogyan használják látogatóink a weboldalt (pl. mely oldalak a leglátogatottabbak, hol hagyják el az oldalt stb.). Az adatokat a Google Analytics szolgáltatás segítségével dolgozzuk fel.',
        'p2' => 'Ezek a cookie-k csak akkor aktiválódnak, ha Ön hozzájárult használatukhoz a cookie bannerben.',
        'legal' => 'Jogalap: GDPR 6. cikk (1) bekezdés a) – hozzájárulás',
    ],
    'c' => [
        'title' => 'c) Marketing cookie-k (opcionálisan a jövőben)',
        'p1' => 'Ezek a cookie-k célja, hogy az Ön érdeklődési körének megfelelő hirdetéseket jelenítsenek meg, vagy nyomon kövessék a látogatói szokásait különböző weboldalakon.',
        'p2' => 'Jelenleg ezeket nem használjuk, de fenntartjuk a jogot a jövőbeni alkalmazásukra, előzetes hozzájárulás alapján.',
    ],
    'section4' => [
        'h2' => 'Tanfolyam díjak',
        'th1' => 'Tanfolyam típus',
        'th2' => 'Díj (Ft)',
        'row1' => ['name' => 'GKI tehergépkocsi-vezetői továbbképző vizsgás (CT)',
        'price' => '159.000',
    ],
    'section6' => [
        'h2' => '6. Adatokhoz való hozzáférés, adattovábbítás',
        'p1' => 'A személyes adatokhoz kizárólag az adatkezelő és annak megbízott munkatársai férhetnek hozzá.',
        'p2' => 'Az adatok tárhelyszolgáltató partnerünk szerverein kerülnek tárolásra, amely biztosítja az adatok biztonságát. Az Ön adatai harmadik fél számára nem kerülnek átadásra marketing vagy egyéb célra.',
    ],
    'section7' => [
        'h2' => '7. Külső szolgáltatók',
        'p' => 'Weboldalunk működtetéséhez a következő külső szolgáltatókat használjuk:',
        'li1' => 'Tárhelyszolgáltató: Ezit',
        'li2' => 'Google Analytics (a jövőben): Látogatottsági adatok elemzése céljából. A Google Analytics nem gyűjt név szerinti adatokat, de IP-cím alapján anonim statisztikát készít.',
    ],
    'impressum-page' => [
        'title' => 'Impresszum',
        'h2' => 'Cégadatok',
        'name_label' => 'Cégnév: ',
        'name' => 'RDR 2003 Kft',
        'address_label' => 'Székhely: ',
        'address' => 'Tópark utca 1/A., Törökbálint, Hungary',
        'email_label' => 'Email: ',
        'email' => 'rdr2003@rdr2003.hu',
    ],
    'hosting' => [
        'h2' => 'Tárhelyszolgáltató',
        'provider_label' => 'Szolgáltató neve: ',
        'provider' => 'Websupport Magyarország Kft.',
        'address_label' => 'Székhely: ',
        'address' => 'H-1119 Budapest, Fehérvári út 97-99.',
        'email_label' => 'Email: ',
        'email' => 'info@ezit.hu',
        'phone_label' => 'Telefon: ',
        'phone' => '+36 1 700 40 30',
        'website_label' => 'Web cím: ',
        'website' => 'https://www.ezit.hu',
    ],
    'legal' => [
        'h2' => 'Jogi információk',
        'registry_label' => 'Nyilvántartó hatóság: ',
        'registry' => 'Fővárosi Törvényszék Cégbírósága',
        'license_label' => 'Működési engedély száma: ',
        'license' => 'KE-12345/2025',
        'chamber_label' => 'Kamarai tagság: ',
        'chamber' => 'Budapesti Kereskedelmi és Iparkamara',
        'chamber_number_label' => 'Kamarai nyilvántartási szám: ',
        'chamber_number' => 'BU123456',
    ],
    'disclaimer' => [
        'h2' => 'Felelősségi nyilatkozat',
        'p' => 'Az RDR 2003 Kft. mindent megtesz annak érdekében, hogy a weboldalon megjelenő információk pontosak és naprakészek legyenek, azonban nem vállal felelősséget az esetleges tévedésekért vagy hiányosságokért. A weboldal tartalma szerzői jogvédelem alatt áll.',
    ],
    'last_updated' => 'Utolsó frissítés: 2025. január 1.',
    ],
    'privacy-policy' => [
        'title' => 'Adatkezelési tájékoztató',
        'h2' => '1. Bevezetés',
        'p' => 'Jelen tájékoztató célja, hogy ismertesse, hogyan kezeljük az Ön személyes adatait, amelyeket a weboldalunkon keresztül – különösen a kapcsolatfelvételi űrlap kitöltésével – ad meg. Az adatkezelés során a vonatkozó jogszabályoknak megfelelően járunk el, különösen az (EU) 2016/679 rendelet (GDPR) és a 2011. évi CXII. törvény (Info tv.) alapján.',
    ],
    'section8' => [
        'h2' => '8. Az érintettek jogai',
        'p' => 'Ön jogosult:',
        'li1' => 'Tájékoztatást kérni az adatkezelésről',
        'li2' => 'Hozzáférni a kezelt adatokhoz',
        'li3' => 'Kérni az adatok helyesbítését, törlését vagy korlátozását',
        'li4' => 'Tiltakozni az adatkezelés ellen',
        'li5' => 'Hozzájárulását bármikor visszavonni',
        'li6' => 'Panaszt tenni a Nemzeti Adatvédelmi és Információszabadság Hatóságnál (NAIH)',
        'naih' => 'NAIH elérhetősége:',
        'address' => 'Cím: 1055 Budapest, Falk Miksa utca 9-11.',
        'phone' => 'Telefon: +36 (1) 391-1400',
        'email' => 'Email: ugyfelszolgalat@naih.hu',
    ],
    'section9' => [
        'h2' => '9. Cookie-k (sütik)',
        'p1' => 'Weboldalunk sütiket (cookie-kat) használ a felhasználói élmény javítása érdekében. Az elengedhetetlenül szükséges cookie-k biztosítják az oldal működését, míg a statisztikai vagy marketing célú cookie-k csak az Ön kifejezett hozzájárulásával aktiválódnak.',
        'p2' => 'A sütik kezeléséről részletesen tájékoztatjuk Önt külön dokumentumban:',
        'link' => 'Cookie (sütik) tájékoztató',
    ],
    'section10' => [
        'h2' => '10. Adatbiztonság',
        'p' => 'Mindent megteszünk annak érdekében, hogy az Ön adatait a lehető legnagyobb biztonságban kezeljük. Weboldalunk HTTPS titkosítással működik, az adatokhoz való hozzáférés korlátozott, és megfelelő technikai és szervezési intézkedéseket alkalmazunk az adatvédelem érdekében.',
    ],
    'last_updated' => 'Utolsó frissítés dátuma: 2025. január 1.',
    ],
    'gki-page' => [
        'title' => 'GKI Tanfolyamok',
        'h2' => 'Vizsga nélküli GKI tanfolyam',
        'type_label' => 'Képzés típusa: ',
        'type' => 'E-learning (online, E-titán rendszerben) – otthon önállóan elvégezhető.',
        'sim_label' => 'Szimulátoros tanfolyam: ',
        'sim' => '5 óra (kötelező a GKI kártya megszerzéséhez). Időpontot a tanfolyam elkezdése után egyeztetünk.',
        'exam_label' => 'Vizsga: ',
        'exam' => 'Modulzáró teszt a tananyag végén.',
        'li1' => 'Csak érvényes magyarországi GKI kártyával rendelkező hallgatók vehetnek részt.',
        'li2' => 'Akinek nincs GKI kártyája, csak vizsgás tanfolyamot választhat.',
        'li3' => 'A meghosszabbítás a kártya lejárta előtt legkorábban 6 hónappal lehetséges.',
        'li4' => 'Az új kártya érvényessége a régi lejáratától számítódik.',
    ],
    'row2' => [
        'name' => 'Nem tartányos + tartányos alaptanfolyam és szakosítás',
        'price' => '255 000',
    ],
    'row3' => [
        'name' => 'Nem tartányos + tartányos ismeretfelújító képzés',
        'price' => '195 000',
    ],
    'row4' => [
        'name' => 'Tartányos szakosítás meglévő NT képesítéssel',
        'price' => '158 000',
    ],
    'row5' => [
        'name' => 'ADR NT1 és NT7 (robbanó + radioaktív)',
        'price' => '95 000',
    ],
    'row6' => [
        'name' => 'GKI összevont továbbképző vizsga nélküli (CDTVN)',
        'price' => '189.000',
    ],
    'discount_label' => 'Kedvezmény:',
            'discount' => 'Kedvezménykártyával 10.000 Ft kedvezményt biztosítunk!',
            'valid_from' => 'Érvényes: 2024. január 26-tól',
        ],

        'section5' => [
        'h2' => 'Jelentkezés',
        'li1' => 'Melyik tanfolyamra jelentkezik',
        'li2' => 'Számlázási adatok',
        'li3' => 'Kapcsolattartó neve és elérhetősége',
    ],
    'hu-courses' => [
        'title' => 'GKI Tanfolyam',
        'desc' => 'Jogosítvánnyal rendelkező gépjárművezetők számára kötelező továbbképzés.',
    ],
    'iranyito' => [
        'title' => 'Szakmai Irányító',
        'desc' => 'Vállalkozások szállítási tevékenységét felügyelő, képesített szakemberek képzése.',
    ],
    'av-page' => [
        'title' => 'AV Tanfolyamok',
        'h2' => 'Tanfolyami díjak',
        'th1' => 'Képzés típusa',
        'th2' => 'Díj (Ft)',
        'row1' => ['name' => 'Árufuvarozói szakmai irányítói alapképesítő (AVN)',
        'price' => '299.000',
    ],
    'valid_from' => 'Érvényes: 2023. október 01-től',
        ],

        'format' => [
        'h2' => 'Képzés formája',
        'p' => 'A szakmai irányítói tanfolyam online formában végezhető az E-titán rendszer felületén.',
        'li1' => 'Nincs helyhez vagy időhöz kötve, saját tempóban végezhető.',
        'li2' => 'Regisztráció után azonnal elérhető.',
    ],
    'consultation' => [
        'h2' => 'Konzultációs nap',
        'p' => 'Az online tananyag mellett egy egynapos személyes konzultációs alkalmat is biztosítunk:',
        'li1' => 'Időpont: szombati vagy vasárnapi napokon.',
        'li2' => 'Helyszín: 2045 Törökbálint, Tópark utca 1/A, földszint (RDR 2003 Kft.).',
    ],
    'exam' => [
        'h2' => 'Vizsga információk',
        'p' => 'A tanfolyam elvégzése után kötelező vizsgát tenni a vizsgaközpontban.',
        'li1_label' => 'Továbbképzés esetén:',
        'li1' => 'Számítógépes teszt és esettanulmány.',
        'li2_label' => 'Alapképzés esetén:',
        'li2' => 'Számítógépes teszt, esettanulmány és szóbeli vizsga.',
        'note_label' => 'Fontos:',
        'note' => 'Vizsgaidőpont csak az online tanfolyam sikeres teljesítése után foglalható!',
    ],
    'registration' => [
        'h2' => 'Jelentkezés',
        'li1' => 'Tanfolyam típusának megadása',
        'li2' => 'Számlázási adatok',
        'li3' => 'Kapcsolattartó neve és elérhetősége',
    ],
    'adr-austria-page' => [
        'title' => 'Osztrák ADR Tanfolyam',
        'h2' => 'Szabad időpontjaink',
    ],
    'info' => [
        'h2' => 'Fontos információk',
        'li1' => 'Csak magyarul beszélő, olvasó és író hallgatókat tudunk fogadni.',
        'li2' => 'Nem magyar születésű jelentkező esetén szükséges a személyi igazolvány másolata.',
        'li3' => 'Magyar nyelvű oktatás és vizsga, osztrák ADR bizonyítvánnyal (5 évig érvényes).',
    ],
    'travel' => [
        'h2' => 'Utazás',
        'p' => 'Képzési napokon reggel 7:00-kor indulás Törökbálint, Spar parkolóból. Megállók: Tata (Shell kút), Győr (MOL kút).',
    ],
    'location' => [
        'h2' => 'Képzés helyszíne',
        'place' => 'EDER PANSION',
        'address' => '2460 Bruck ad Leitha, Altstadt 19., Österreich',
        'note' => 'Visszaérkezés kb. 18:30 (vasárnap kb. 17:30). Képzés minden napon, az utolsó napon vizsga.',
    ],
    'benefits' => [
        'h2' => 'Tanfolyam előnyei',
        'li1' => 'Valós, gyakorlati tudás megszerzése.',
        'li2' => 'Jelentős adminisztrációs könnyítés a magyar rendszerhez képest.',
        'li3' => '30 tesztkérdés, magyar nyelvű segédanyag használata megengedett.',
    ],
    'prices' => [
        'h2' => 'Árak',
        'th1' => 'Képzés típusa',
        'th2' => 'Díj (Ft)',
        'row1' => ['name' => 'Nem tartányos alaptanfolyam / ismeretfelújítás',
        'price' => '158 000',
    ],
    'pdf' => 'Tanfolyami díjak (PDF letöltése)',
        ],

        'accommodation' => [
        'h2' => 'Szállás',
        'place' => 'EDER PANSION',
        'with_breakfast' => 'reggelivel',
        'li1' => '1 ágyas szoba: 44 Euro / 17.000 Ft',
        'li2' => '2 ágyas szoba: 33 Euro / 13.000 Ft',
        'li3' => '3 ágyas szoba: 31 Euro / 12.000 Ft',
        'note' => 'Lemondási határidő: a képzés hetében, hétfőn.',
    ],
    '404' => [
        'title' => '404',
        'line1' => 'Úgy tűnik nem található semmi ezen a helyen.',
        'line2' => 'Lehet, hogy ezt az oldalt törölték, vagy nem is létezett.',
    ],
    'rent-classroom' => [
        'title' => 'Lépjen velünk kapcsolatba',
        'phone' => '+36 30 878 9488',
        'email' => 'rdr2003@rdr2003.hu',
        'address' => 'Törökbálint, Tópark u. 1a, 2045',
    ],
    'services' => [
        'passenger' => 'Személyszállításra kialakítva',
        'capacity' => '6–9 fő számára kényelmes',
        'ac' => 'Klimatizált utastér',
        'trunk' => 'Nagy csomagtér',
        'trips' => 'Rövid és hosszú utakra is alkalmas',
        'license' => 'B-s jogosítvánnyal vezethető',
        'driver' => 'Sofőrrel is kérhető',
        'ideal' => 'Ideális céges utakhoz, kirándulásokhoz',
    ],
    'desc' => [
        'h1' => 'Kényelmes személyszállító furgon bérlése',
        'p1' => 'Lehetőséget kínálunk kényelmes, személyszállításra alkalmas furgon bérlésére...',
        'h2' => '6–9 fő számára tervezve',
        'p2' => 'A furgon 6–9 fő szállítására alkalmas, klimatizált, tágas utastérrel...',
        'h3' => 'Ideális céges utakhoz, kirándulásokhoz',
        'p3' => 'Kiváló választás céges rendezvényekre, csapatépítőkre, iskolai kirándulásokhoz...',
        'h4' => 'Rugalmas bérlési lehetőségek',
        'p4' => 'Bérléskor rugalmas feltételeket kínálunk, akár sofőrrel, akár sofőr nélkül...',
        'h5' => 'Vegye fel velünk a kapcsolatot!',
        'p5' => 'Ha megbízható, kényelmes és jól felszerelt személyszállító járművet keres...',
    ],
    'vanrent' => [
        'title' => 'Lépjen velünk kapcsolatba',
        'phone' => '+36 30 878 9488',
        'email' => 'rdr2003@rdr2003.hu',
        'address' => 'Törökbálint, Tópark u. 1a, 2045',
    ],
];